// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MatchUIClient is the client API for MatchUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchUIClient interface {
	// ListEngineSpecs returns a list of Matching Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (MatchUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type matchUIClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchUIClient(cc grpc.ClientConnInterface) MatchUIClient {
	return &matchUIClient{cc}
}

func (c *matchUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (MatchUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MatchUI_ServiceDesc.Streams[0], "/v1.MatchUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &matchUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MatchUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type matchUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *matchUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *matchUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.MatchUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchUIServer is the server API for MatchUI service.
// All implementations must embed UnimplementedMatchUIServer
// for forward compatibility
type MatchUIServer interface {
	// ListEngineSpecs returns a list of Matching Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, MatchUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedMatchUIServer()
}

// UnimplementedMatchUIServer must be embedded to have forward compatible implementations.
type UnimplementedMatchUIServer struct {
}

func (UnimplementedMatchUIServer) ListEngineSpecs(*ListEngineSpecsRequest, MatchUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedMatchUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedMatchUIServer) mustEmbedUnimplementedMatchUIServer() {}

// UnsafeMatchUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchUIServer will
// result in compilation errors.
type UnsafeMatchUIServer interface {
	mustEmbedUnimplementedMatchUIServer()
}

func RegisterMatchUIServer(s grpc.ServiceRegistrar, srv MatchUIServer) {
	s.RegisterService(&MatchUI_ServiceDesc, srv)
}

func _MatchUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MatchUIServer).ListEngineSpecs(m, &matchUIListEngineSpecsServer{stream})
}

type MatchUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type matchUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *matchUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MatchUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MatchUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchUI_ServiceDesc is the grpc.ServiceDesc for MatchUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MatchUI",
	HandlerType: (*MatchUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _MatchUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _MatchUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "match-ui.proto",
}
